# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bcda5e7678104cff55d985652fd0bcc41efdcb6cca9d8906fb2ce2460149867cf3ac81dbe93c4d99d01d918b282f473816c4b9110ab2cc93661f6e7ac2bead9

test:
  secret_key_base: f6ed707e5037925838d0c2bb031377cdf275033b9e0f40437c9e5ca66c30e4206f90e295019e6fd6bac5c9898ce96d8412dea7471e0b4fc7d46b377640e90251

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
